name: Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Get the short commit hash
      - name: Get Short Commit Hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build_tzstamp_server
        uses: docker/build-push-action@v6
        with:
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/fraidev/smsb:latest
            ghcr.io/fraidev/smsb:${{ env.commit_hash }}
